### ISSUE TITLE
Add option for fixed-point encoding with additive shift

### ISSUE THREAD

**Issue by degregat** [mozilla/libprio#106]
To use prio as a backend for e.g. federated learning, support for fixed-point encoding would be nice. Since we only have summation of bits, preserving sign bits is not an option so an additive shift should be applied to the encoding.

I started work on this and will do a (draft) PR when it's presentable.

**Comment by degregat** [comment]
PR #108 does this

**Comment by henrycg** [comment]
See comment in #108.
