### ISSUE TITLE
libprio does not build on non-64bit and noopt (-O0) builds

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#15]
I haven't tried directly with Scons but I suspect it'll fail in the same way:

https://treeherder.mozilla.org/logviewer.html#?job_id=195528704&repo=try&lineNumber=32847

14:45:50 INFO - /builds/worker/workspace/build/src/third_party/prio/prio/client.c:48: error: undefined reference to 'next_power_of_two'
32848 14:45:50 INFO - /builds/worker/workspace/build/src/third_party/prio/prio/config.c:130: error: undefined reference to 'next_power_of_two'
32849 14:45:50 INFO - /builds/worker/workspace/build/src/third_party/prio/prio/server.c:255: error: undefined reference to 'next_power_of_two'
32850 14:45:50 INFO - /builds/worker/workspace/build/src/third_party/prio/prio/server.c:282: error: undefined reference to 'next_power_of_two' 

I'll spin up an Android dev environment at some point, this platform is not really a top priority for me at the moment but will be good to have it eventually.

**Comment by henrycg** [comment]
The symbol it's failing to find is an `inline`d function, which might be screwing things up. We could try moving the function into a `.c` file and seeing if it compiles then.

**Comment by rhelmer** [comment]
Hm, so this is actually higher-priority for me now because it's busting a few of our more esoteric builders as well (memory sanitizer "asan" builds, and cross-compiled Linux->macOS builds)

https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=492f05d220b1495339691c2bf6c74c106a89b867

I'll take a look at this now

**Comment by rhelmer** [comment]
Hm, https://stackoverflow.com/questions/16245521/c99-inline-function-in-c-file/16245669#16245669 suggests that `static` is probably fine, @henrycg what is the reason for having it be `inline`?

If there's a good reason then I think we just need to duplicate the definition. Not sure why this only shows up on certain platforms, probably a compiler setting or something.

**Comment by rhelmer** [comment]
Oh, hm. I wonder if this is related to the optimization flag being passed to the compiler... gcc won't inline things when optimizations are completely turned off, so it needs to be declared somewhere...

I'll see if duplicating it in a header file works.

**Comment by rhelmer** [comment]
Ah, ok so I can repro using Scons if I set optimization to `-O0`, I'll see if I can fix...

**Comment by henrycg** [comment]
I didn't inline this code for any particular reason... I won't be able to take a look at this until tonight, but however you want to fix it is okay with me.

**Comment by rhelmer** [comment]
Hm, ok yeah this seems to work:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4564af0332e9e17b49823a40fd02d4c15532fb80

**Comment by rhelmer** [comment]
@henrycg ok cool I just made them `static inline`, from what I can tell it'll do the trick. I'll ask a few of the experts on this stuff around mozilla too just to double check.
