### ISSUE TITLE
add basic CI for libprio

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#21]
Since we're building libprio in Firefox there is OK coverage for basic stuff, but I think it'd make everyone's lives easier if there was some basic CI like Travis or CircleCI etc. that compiled, linted, ran tests, etc. when folks opened PRs and after merges, so it doesn't require someone to remember to do this locally before merging.

We'd catch this on import to Firefox but that could be quite a long lag time :)

I'll have a bit of free time to do this and have done it before so can set it up if you like.

**Comment by henrycg** [comment]
Yes, it would be great if you could set this up! I have been meaning to rewrite the `ptest` utility using googletest as well, since it has some features that the current test harness doesn't (run a single test by name, etc.).

**Comment by rhelmer** [comment]
Huh, I didn't know rebasing + force-pushing my commit would spam the issue like this :)

Anyway I think I have it working in pr #22 now.
