### ISSUE TITLE
automated code coverage, static analysis, fuzzing, style checking, etc.

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#25]
Now that Travis CI is running it'd be pretty easy to add things like test coverage, static analysis tools (clang-tidy and scan-build are OK, there are more), fuzzing, style checking etc.

I know that there is a particular code style already in-place for libprio but I'd very much suggest that some out-of-the-box style using clang-format be used (it comes with a Mozilla style even!) and enforced when PRs are opened. More for the sake of future contributors than as a personal preference (but that too ;)

**Comment by henrycg** [comment]
Using clang-format to enforce the Mozilla C style (or whatever other standard style) sounds like a great idea.

**Comment by rhelmer** [comment]
We have CI now with compilation, tests, and clang-format. Static analysis and fuzzing are pretty complex and probably worth leaving to Firefox and not try to get it going in Travis-CI right now.
