### ISSUE TITLE
windows build failing

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#3]
I noticed this doing tryserver (pre-checkin CI) builds:

`z:/build/build/src/third_party/prio/prio/client.c(10,10): fatal error: 'strings.h' file not found`

- [x] It looks like `<string.h>` is present on Windows, AFAICT `<strings.h>` is an BSD fork that didn't make it's way to Windows. Not 100% sure of the lineage here or what's available to C++ vs. C, it looks like `<string.h>` is available on macOS and Windows for C code at least.
- [x] `std::isxdigit` doesn't seem to work on Windows but `isxdigit` does

**Comment by henrycg** [comment]
It looks like `isxdigit` is available in `<ctype.h>`, which should be available on Windows.

**Comment by rhelmer** [comment]
Tryserver run with `<string.h>` instead of `<string.h>`, going to try plain `isxdigit` and see if that works, since I think we might already `#include <ctype.h>` somewhere in the DOM build machinery (it's a bit involved):
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4b019f9365e07c8544bc37d5cbcfb5038d9bda25

**Comment by rhelmer** [comment]
Progress! Looks like it's some problem with missing msgpack symbols now, hm.

**Comment by rhelmer** [comment]
Looks like the symbol it wants is defined in `mpcpucache.c` which isn't in the prio `moz.build`, let's see if that helps: https://treeherder.mozilla.org/#/jobs?repo=try&revision=bbaf8db92d3445bb8be7d680be811f80ffac2045

**Comment by rhelmer** [comment]
Hm, yeah so that gets further still:

https://treeherder.mozilla.org/logviewer.html#?job_id=192842378&repo=try&lineNumber=61835-61838

```
18:55:41     INFO -  z:/build/build/src/clang/bin\lld-link.exe: error: could not open z:/build/build/src/obj-firefox/dist/lib/nspr4.lib.lib: no such file or directory
18:55:41     INFO -  z:/build/build/src/clang/bin\lld-link.exe: error: could not open z:/build/build/src/obj-firefox/dist/lib/plc4.lib.lib: no such file or directory
18:55:41     INFO -  z:/build/build/src/clang/bin\lld-link.exe: error: could not open z:/build/build/src/obj-firefox/dist/lib/plds4.lib.lib: no such file or directory
```

**Comment by rhelmer** [comment]
OK I pushed the latest `moz.build` that we're testing over in issue #4, looks like we have a good windows build \o/

https://treeherder.mozilla.org/#/jobs?repo=try&revision=362a0029cf27de88c4789f683a3d3138f662b9c1

I'll check in on the test runs later.

**Comment by rhelmer** [comment]
There are 3 test failures, pretty sure they are all intermittent. Once everything has settled down I will go through this issue and turn it into the various amended hg commits and libprio PRs as necessary.

**Comment by rhelmer** [comment]
This is working \o/ https://treeherder.mozilla.org/#/jobs?repo=try&revision=5da61e100e5d5e021b0893ba44452624f3c6ef98

All related PRs are merged and patches have been rebased into my Firefox+libprio integration patch as necessary, so I think we're done here.

Thanks all!
