### ISSUE TITLE
Set up Travis-CI to test libprio on Windows

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#42]
Windows isn't supported on Travis-CI, but AppVeyor does and is free for open-source projects: https://github.com/marketplace/appveyor

Firefox CI tests Win64+Clang, but will not catch issues in eventual MSVC support (issue #17). Also Firefox has its own build system so won't test that libprio can be built standalone on Windows (issue #37 or just in general).

**Comment by rhelmer** [comment]
OK, I think I figured out how to disable this on branches without an `appveyor.yml`, so it'll stop making trouble in other PRs.

**Comment by rhelmer** [comment]
Travis-CI just announced support for Windows, probably worth considering this before bothering with AppVeyor just for Windows support: https://blog.travis-ci.com/2018-10-11-windows-early-release?utm_source=reddit&utm_medium=web&utm_campaign=windows_early_release

**Comment by rhelmer** [comment]
I think we should just use Travis for this rather than having two separate CIs.

**Comment by henrycg** [comment]
Closed by #111
