### ISSUE TITLE
Configure travis-ci to use Coverity Scan

### ISSUE THREAD

**Issue by henrycg** [mozilla/libprio#55]
Since libprio is open source, we should be able to get a free Coverity account and the configure travis-ci to run the scans automatically:
  https://scan.coverity.com/travis_ci

**Comment by rhelmer** [comment]
This is not a good first issue it turns out - need to get permission from Mozilla's Github admins to enable this. However there might be a different service we can use soon to run Coverity from GH, waiting for details on that.

**Comment by henrycg** [comment]
Do you know what the status of this is? It would be great to get Coverity running.

**Comment by rhelmer** [comment]
Still waiting for details - the Mozilla GH admins did not want to enable the free Coverity service for the moment. I'll poke Mozilla security folks about the status.
