### ISSUE TITLE
use types from <stdint.h> for integer types instead of implementation-defined

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#64]
@hsivonen mentioned this in a recent review: https://phabricator.services.mozilla.com/D16267#412614

> Seems unfortunate that libprio uses integer types whose size is implementation-defined instead of using the types from <stdint.h> (in this case uint64_t).

@henrycg any reason not to make this change? I think this basically means giving up on C90 support and requiring C99. The only C90 compiler in wide use that I am aware of is MSVC (issue #17) and I am less convinced that this is important given that clang works well on that platform now.

**Comment by henrycg** [comment]
Yes, this sounds like a good idea and I am in favor. It probably wouldn't be that difficult of a change to make, and would avoid the portability problems we saw earlier.
