### ISSUE TITLE
rewrite browser-test.c / encode-once.js for latest API

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#7]
I was just taking a look at `browser-test.c` and `encode-once.js`, I took a quick stab at rewriting the latter:

```
/*
 * Copyright (c) 2018, Henry Corrigan-Gibbs
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

ChromeUtils.import('resource://gre/modules/Services.jsm');

let [publicKeyA, publicKeyB, batchID, param1, param2, param3] = arguments;

Services.prefs.setStringPref('prio.publicKeyA', publicKeyA);
Services.prefs.setStringPref('prio.publicKeyB', publicKeyB);

async function test() {
  let params =  {
    'browserIsUserDefault': Boolean(param1),
    'safeModeUsage': Boolean(param2),
    'startupCrashDetected': Boolean(param3)
  };

  let result = await PrioEncoder.encode(batchID, params);
}

test().then(console.log("finished"));
```

This still needs to return the correct output, but I was doing a quick test run with is and seeing:

`Hit MOZ_CRASH(NSS_Shutdown failed) at /Users/rhelmer/src/mozilla-central/xpcom/build/XPCOMInit.cpp:1044`

I suspect that this has to do with how NSS gets init'd in the xpcshell environment, as I am seeing no problems when running equivalent code in the browser.

**Comment by rhelmer** [comment]
Ah, here's where it's crashing:

https://searchfox.org/mozilla-central/rev/aff5d4ad5d7fb2919d267cbc23b1d87ae3cf0110/xpcom/build/XPCOMInit.cpp#1036-1049

This assert is being hit because I am using a debug build, I will follow up with NSS folks to see if we're missing something here...

**Comment by rhelmer** [comment]
Hm so ignoring the NSS shutdown thing for the moment, I think this should be equivalent to the previous `encode-once.js` but it doesn't seem to pass `browser-test`:

```
/*
 * Copyright (c) 2018, Henry Corrigan-Gibbs
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

ChromeUtils.import('resource://gre/modules/Services.jsm');

let [publicKeyA, publicKeyB, batchID, param1, param2, param3] = arguments;

Services.prefs.setStringPref('prio.publicKeyA', publicKeyA);
Services.prefs.setStringPref('prio.publicKeyB', publicKeyB);

async function test() {
  let params =  {
    'browserIsUserDefault': Boolean(param1),
    'safeModeUsage': Boolean(param2),
    'startupCrashDetected': Boolean(param3)
  };

  try {
    let result = await PrioEncoder.encode(batchID, params);

    let textEncoder = new TextEncoder();
    const toHexString = bytes =>
      bytes.reduce((str, byte) => str + byte.toString(16).padStart(2, '0'), '');

    console.log(toHexString(textEncoder.encode(result.a)) + ',$' + toHexString(textEncoder.encode(result.b)));
    console.log('');
  } catch(e) {
    console.log('Failure.', e);
    console.log(v);
  }
}

test().then();
```

**Comment by franziskuskiefer** [comment]
> Ah, here's where it's crashing:

`rand_clear`, which is shutting down the instance of NSS you use is probably not called on time. That's why I mentioned that you could use PSM to get an instance of NSS (then clean-up is guaranteed on xpcom shutdown) [1]. That would require some changes here but would be the easiest way to get an instance of NSS in Firefox that's handled properly.

[1] https://searchfox.org/mozilla-central/rev/aff5d4ad5d7fb2919d267cbc23b1d87ae3cf0110/security/manager/ssl/nsNSSComponent.cpp#88

**Comment by henrycg** [comment]
@rhelmer Which build of the browser are you using for testing? I can build it and try to debug the script.

**Comment by rhelmer** [comment]
@henrycg this is the latest changeset on bug 1421501, should be able to pull it with:
`hg pull -r c3124c62ccc4bae4bcab1e895c89c27c457048e4 https://reviewboard-hg.mozilla.org/gecko`

I didn't dig into it much last night, I have a debug build which does produce a lot more output on stdout though, I'll try with an opt build too.

**Comment by henrycg** [comment]
A couple of things:
* The line with bytes.reduce should read:
` bytes.reduce((str, byte) => str + byte.toString(16).padStart(2, '0'), '') + ',';`
so that there is a comma after every pair of hex digits. (The browser-test tool expects the strings in this format.)
* I suspect that there is something going wrong with the conversion of bytes to hex strings. The strings that `PrioEncoder.encode` produces should be random strings, but the strings I see in the output have way more `c` characters than I would expect in a random string.

**Comment by henrycg** [comment]
This version of `encode_once.js` seems to work for me. (Forgive me for the poor JS skills.) It does seem like `TextEncoder` wasn't doing quite the right thing...

```
/*
 * Copyright (c) 2018, Henry Corrigan-Gibbs
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

ChromeUtils.import('resource://gre/modules/Services.jsm');

let [publicKeyA, publicKeyB, batchID, param1, param2, param3] = arguments;

Services.prefs.setStringPref('prio.publicKeyA', publicKeyA);
Services.prefs.setStringPref('prio.publicKeyB', publicKeyB);

async function test() {
  let params =  {
    'browserIsUserDefault': Number(param1),
    'safeModeUsage': Number(param2),
    'startupCrashDetected': Number(param3)
  };

  try {
    let result = await PrioEncoder.encode(batchID, params);

    function toArr(bStr) {
      var len = bStr.length;
      var u8_array = new Uint8Array(len);
      for (var i = 0; i < len; i++) {
        u8_array[i] = bStr.charCodeAt(i);
      }
      return u8_array;
    }
    const toHexString = bytes =>
      bytes.reduce((str, byte) => str + byte.toString(16).padStart(2, '0') + ',', '');

    console.log(toHexString(toArr(result.a)) + '$' + toHexString(toArr(result.b)));
    console.log('');
  } catch(e) {
    console.log('Failure.', e);
    console.log(v);
  }
}

test().then();
```

**Comment by rhelmer** [comment]
Ah too bad about `TextEncoder`, I'll have to dig into that more... I should have got the tests running before I promoted it :)

Thanks!

**Comment by rhelmer** [comment]
Totally agree that we should have this test in the mozilla-central tree, this is something I can do... was hoping we could limp along a bit more since you already put the work into the `browser-test` thing :)

**Comment by rhelmer** [comment]
(adding these sorts of test-only functions is pretty common from what I see poking around the WebIDL, they tend to be behind prefs so they aren't generally available outside of the test framework).

I'll give it a shot once I have a moment.

**Comment by henrycg** [comment]
Cool. I'm happy to help out with the C++ code that will link up to libprio.
