### ISSUE TITLE
Travis should automatically fetch the latest version of NSS

### ISSUE THREAD

**Issue by henrycg** [mozilla/libprio#70]
Right now, the `.travis.yml` file points to a non-permanent version of NSS. Whenever Mozilla releases a new version of NSS, the file name changes and our Travis CI builds all fail. It would be nice to have the tests automatically use the latest version of NSS.

**Comment by rhelmer** [comment]
It might just be best overall to download the NSS source and build it. Bonus points for caching the built artifact in CI so it doesn't need to be compiled every time.

The only other reasonable option I can think of is to add a source for Debian in apt and then either install the binary package or (preferable really) to build the source package. The thing I don't like about this option is that the package wasn't built for the version of Ubuntu that Travis supports (Trusty) so it could introduce difficult-to-diagnose problems that we can't really complain to anyone about.

The latter is basically equivalent to what we're doing now, but with more hassle around configuring apt etc. and I don't think there's really any benefit.

**Comment by henrycg** [comment]
Since we're moving away from Travis CI anyways, I will close this one.
