### ISSUE TITLE
Switch from Travis CI to Taskcluster

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#85]
I've spent some time this week debugging issues with Travis CI (some of the github admins at Mozilla needed to do some work), it seems to still not be working... I see builds happening and get emailed about them (since Travis is set up via my account), but it's not working in PRs.

I was talking to a co-worker earlier about the state of GitHub integration for Mozilla's Taskcluster CI, and it sounds like there are quite a few projects using it successfully. I think it'd be pretty easy to switch over.

This would also allow us to use a modern Linux distro, as Travis is stuck on an older Ubuntu we've had to do extra work to make sure there are newish versions of our build dependencies.

**Comment by rhelmer** [comment]
Well shoot Travis just started working in https://github.com/mozilla/libprio/pull/84 - I still think we should switch but it's less urgent then.

**Comment by henrycg** [comment]
Thanks for working on this, Rob!

**Comment by rhelmer** [comment]
I got Travis CI working again in PR #86 by resetting to Bionic, I think we've hit the end of the road with the approach of fetching the latest Debian NSS packages.

Issue #79 I think will be a better approach, for the moment I switched back to using system packages so we're not blocking new PRs from merging. We do want to have more modern versions of msgpack and NSS though.

**Comment by henrycg** [comment]
Duplicate of #111
