### ISSUE TITLE
Upgrade to clang-format 9.0

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#87]
Currently we use clang-format 3.9 because in https://github.com/mozilla/libprio/commit/ded8b1054b84012676b28772fd7594476652752a this was the latest version on Ubuntu Trusty, which was what Travis CI stuck us with at the time.

Since 52643cefe6662b4099e16a40a057cb60651ab001 we've been on Ubuntu Bionic, so we can upgrade to a much newer version (9.0), which is what Homebrew is at right now as well.

We'll need to re-format the code though since one of the reasons we've been stuck in 3.9 is that there were breaking changes after that version.

**Comment by rhelmer** [comment]
This came up in PR #84 since having to fetch and run an older version is a hassle.

**Comment by degregat** [comment]
I opened a PR (#88) about this. Tests are running fine on my machine, lets see what the CI says.

**Comment by henrycg** [comment]
Fixed by #97
