### ISSUE TITLE
libprio does not build on macOS (with scons)

### ISSUE THREAD

**Issue by rhelmer** [mozilla/libprio#9]
Not super urgent at the moment and I hacked around it, but before I forget:

The macOS instructions in the README no longer work, because the latest `SConstruct` doesn't seem to honor the `LDFLAGS` to find the shared libs and `CPPFLAGS` to find the headers.

Should be pretty trivial to fix, I'll get it when I have a free moment (as I mentioned I just hacked the file to hardcode the paths I get from the homebrew installs)

**Comment by henrycg** [comment]
This should be fixed by PR #10
